version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
      - chmod +x scripts/deploy.sh

  build:
    commands:

      - ./scripts/deploy.sh

artifacts:
  files:
    - '**/*'



