version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
      - set -e
      - echo "Installing global packages..."
      - npm install -g serverless@3 @nestjs/cli

  pre_build:
    commands:
      - echo "Pre-build phase started..."

  build:
    commands:
      - echo "Build phase running..."
      - pwd
      - ls -la

  post_build:
    commands:
      - echo "Build completed successfully at $(date)"