Resources:
  LeaveManagementSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: leave-management/production-new
      Description: Production secrets

      SecretString: !Sub |
        {
          "JWT_SECRET":"dhbrW6d4J6JsEBeNgeJm16xduZOdWd1bMSoF28FzQqy",
          "JWT_EXPIRES_IN":"7d",
          "OFFICE_LAT":"23.103141295479464",
          "OFFICE_LNG":"72.59559139416137",
          "GPG_KEY":"nothing123"
        }

Outputs:
  LeaveManagementSecretArn:
    Value: !Ref LeaveManagementSecret