Resources:
  LeaveManagementSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: leave-management/production-new
      Description: Production secrets

      SecretString: !Sub |
        {
          "JWT_SECRET":"${env:JWT_SECRET}",
          "JWT_EXPIRES_IN":"7d",
          "OFFICE_LAT":"${env:OFFICE_LAT}",
          "OFFICE_LNG":"${env:OFFICE_LNG}"
        }
