service: leave-management-dev-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  timeout: 29
  memorySize: 1024

  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: production

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        # - https://your-frontend-domain.com  # add in production
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: false
      maxAge: 3600

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource:
        - "arn:aws:dynamodb:ap-south-1:*:table/LeaveTypes"
        - "arn:aws:dynamodb:ap-south-1:*:table/Users"
        - "arn:aws:dynamodb:ap-south-1:*:table/Leaves"
        - "arn:aws:dynamodb:ap-south-1:*:table/LeaveLogs"
        - "arn:aws:dynamodb:ap-south-1:*:table/LeaveBalances"

    - Effect: "Allow"
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  auth:
    handler: dist/lambda-auth.handler
    events:
      - httpApi:
          path: /auth/{proxy+}
          method: ANY

  users:
    handler: dist/lambda-users.handler
    events:
      - httpApi:
          path: /users/{proxy+}
          method: ANY

  leaves:
    handler: dist/lambda-leaves.handler
    events:
      - httpApi:
          path: /leaves/{proxy+}
          method: ANY

  leaveTypes:
    handler: dist/lambda-leave-types.handler
    events:
      - httpApi:
          path: /leave-types/{proxy+}
          method: ANY

package:
  individually: true
  patterns:
    - '!**/*.md'
    - '!**/*.map'
    - '!**/node_modules/aws-sdk/**'
    - '!**/node_modules/@prisma/engines/**'
    - '!**/node_modules/.prisma/client/query-engine-*'

    # Prisma binaries (IMPORTANT)
    - 'node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
    - 'node_modules/.prisma/client/query-engine-rhel-openssl-3.0.x'
    - 'prisma/schema.prisma'

    # AWS SDK v3
    - 'node_modules/@aws-sdk/**'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node20
    platform: node
    keepNames: true
    external:
      - aws-sdk
      - fast-crc32c
      - '@node-rs/xxhash'
      - '@node-rs/crc32'
      - '@nestjs/microservices'
      - '@nestjs/websockets/socket-module'
      - sharp
      - bcrypt
      - '@prisma/client'