Resources:

  EmployeesLeavesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "employees-leaves-${AWS::AccountId}"

  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: frontend-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt EmployeesLeavesBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref FrontendOAC

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https

          AllowedMethods:
            - GET
            - HEAD

          CachedMethods:
            - GET
            - HEAD

          ForwardedValues:
            QueryString: false

        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  EmployeesLeavesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmployeesLeavesBucket

      PolicyDocument:
        Version: "2012-10-17"

        Statement:
          - Effect: Allow

            Principal:
              Service: cloudfront.amazonaws.com

            Action:
              - s3:GetObject

            Resource: !Sub "arn:aws:s3:::employees-leaves-${AWS::AccountId}/*"

Outputs:

  EmployeesLeavesBucketName:
    Value: !Ref EmployeesLeavesBucket

  CloudFrontURL:
    Value: !Sub "https://${FrontendDistribution.DomainName}"

  FrontendDistributionId:
    Value: !Ref FrontendDistribution