Resources:
  EmployeesLeavesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: employees-leaves-${aws:accountId}-${sls:stage}

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            MaxAge: 3000

  EmployeesLeavesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmployeesLeavesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "${EmployeesLeavesBucket.Arn}/*"

Outputs:
  EmployeesLeavesBucketName:
    Value: !Ref EmployeesLeavesBucket

  WebsiteURL:
    Value: !GetAtt EmployeesLeavesBucket.WebsiteURL